// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TFG2022Server.Data;

#nullable disable

namespace TFG2022Server.Migrations
{
    [DbContext(typeof(TFG2022Context))]
    [Migration("20220810172659_Added_FamiliaProducto")]
    partial class Added_FamiliaProducto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TFG2022Server.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"), 1L, 1);

                    b.Property<int>("CodigoPostal")
                        .HasColumnType("int");

                    b.Property<int>("Descuento")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poblacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioIdCliente")
                        .HasColumnType("int");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            CodigoPostal = 19285,
                            Descuento = 20,
                            Direccion = "Nerja noseque nosecuanto",
                            Poblacion = "Nerja",
                            UsuarioIdCliente = 1
                        },
                        new
                        {
                            ClienteId = 2,
                            CodigoPostal = 79852,
                            Descuento = 50,
                            Direccion = "Servilla cale noseweqe avenida tu",
                            Poblacion = "Torre",
                            UsuarioIdCliente = 2
                        },
                        new
                        {
                            ClienteId = 3,
                            CodigoPostal = 59267,
                            Descuento = 10,
                            Direccion = "Torremolainos bar misisipi",
                            Poblacion = "Torremolinos",
                            UsuarioIdCliente = 3
                        });
                });

            modelBuilder.Entity("TFG2022Server.Entities.FamiliaProducto", b =>
                {
                    b.Property<int>("FamiliaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FamiliaID"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FamiliaID");

                    b.ToTable("FamiliaProductos");
                });

            modelBuilder.Entity("TFG2022Server.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"), 1L, 1);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Apellidos = "Perico",
                            Contraseña = "9shjdc78",
                            Dni = "12457896G",
                            Email = "sdasdf@sdkfjsd.com",
                            FechaNacimiento = new DateTime(2022, 8, 10, 19, 26, 59, 108, DateTimeKind.Local).AddTicks(2712),
                            Nombre = "Alberto",
                            Rol = "cliente",
                            Telefono = 154789632
                        },
                        new
                        {
                            UsuarioId = 2,
                            Apellidos = "lololol",
                            Contraseña = "asdasd",
                            Dni = "14728539M",
                            Email = "askjdhasdj@youtc,on",
                            FechaNacimiento = new DateTime(1974, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "pepep",
                            Rol = "cliente",
                            Telefono = 678867678
                        },
                        new
                        {
                            UsuarioId = 3,
                            Apellidos = "Frefre",
                            Contraseña = "312789adshjk",
                            Dni = "123890756D",
                            Email = "234980@fj.ocm",
                            FechaNacimiento = new DateTime(2000, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Yoigo",
                            Rol = "Jefe",
                            Telefono = 123789798
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
